### ISSUE TITLE
scripts.lib cannot be found 

### ISSUE THREAD

**Issue by nono0210** [google/riscv-dv#836]
After I have installed all the thing , running cmd with **run --help**, there is error as no module named 'scripts.lib'  I am using anaconda python3

thanks

**Comment by hasver** [comment]
Me too

**Comment by erictaur** [comment]
Same here with an anaconda setup (conda 4.10.1)

Exact traceback after cloning the repo + pip installing according to the README:

`(base) -bash-4.1$ run --help
Traceback (most recent call last):
  File "/n/gaylord/v/khtaur/.local/bin/run", line 33, in <module>
    sys.exit(load_entry_point('riscv-dv', 'console_scripts', 'run')())
  File "/n/gaylord/v/khtaur/.local/bin/run", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/afs/eecs.umich.edu/cadre/software/anaconda3-2018.12/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 178, in load
    module = import_module(match.group('module'))
  File "/afs/eecs.umich.edu/cadre/software/anaconda3-2018.12/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/afs/eecs.umich.edu/vlsida/projects/restricted/google/khtaur/riscv-dv/run.py", line 28, in <module>
    from scripts.lib import *
ModuleNotFoundError: No module named 'scripts.lib'`
